### ISSUE TITLE
Help determining LargeFileTransfers port

### ISSUE THREAD

**Issue by Jack-Edwards** [microsoft/SimpleRemote#2]
Hello.  I came across an "issue" while trying out this project today and just wanted to share the solution.  In case it helps someone else down the road.

After getting the SimpleRemoteConsole running on a remote machine, I am to use the RpcClient.Upload() procedure to push files to the remote machine.  This was working great, except that for each upload attempt, the console would output that it was listening to a completely different port: 50118, 50121, 50122, 50124, etc.  This works fine if you disable the firewall.  In case I do not want to disable the firewall, I would still need to open several hundred ports in order to upload over an extended period of time.

Solution: Notice the "Upload" procedure accepts an optional "portNumber" argument.  Passing in a port number other than "0" will force the SimpleRemoteConsole to listen on that port.

**Comment by Jack-Edwards** [comment]
Solved.  See OP.

**Comment by iUnknwn** [comment]
Hi there - just wanted to let you know we added a note in the tutorial about this. Thank you so much for the suggestion.
